const express = require('express')
const Model = require('../models')
const comment = require('./comment')
const homepage = require('./homepage')
const images = require('./image')
const user = require('./user')
const loader = require('./loader')
const router = express.Router()


router.get('/register', user.getRegister)
router.post('/register', user.register)
router.get('/upload', user.checkLogin, images.getUpload)
router.post('/upload', user.checkLogin, images.upload)
router.get('/image/:filename', images.display)
router.get('/image/:filename/edit', user.checkLogin, images.getUpdate)
router.post('/image/:filename/edit', user.checkLogin, images.update)
router.get('/image/:filename/delete', user.checkLogin, images.delete)
router.post('/comment/:filename', user.checkLogin, comment.post)
router.get('/login', user.getLogin)
router.post('/login', user.login)
router.get('/logout', user.logout)
router.get('/user/:username', images.userDisplay)
router.get('/reply/:id', comment.getReply)
router.post('/reply/:id', user.checkLogin, comment.reply)
router.get('/search', homepage.home)
router.get('/account', user.checkLogin, user.getUpdate)
router.post('/account/email', user.checkLogin, user.emailUpdate)
router.post('/account/password', user.checkLogin, user.passwordUpdate)
router.get('/', homepage.home)

router.get('/*', (req, res) => {
    let err = new Error('Page not found')
    res.render('error', { err, req })
})

module.exports = router
